services:
  postgres:
    image: postgres:latest
    container_name: moviehubcontainer
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5431:5432"
    restart: always
    volumes:
      - moviehub-data:/var/lib/postgresql/data
volumes:
  moviehub-data: